### ISSUE TITLE
Add --named-exports flag to create named exports for module indexes

### ISSUE THREAD

**Issue by ryardley** [ryardley/indexr#6]
The following comes from reddit:

[Reddit user theillustratedlife says:](https://www.reddit.com/r/javascript/comments/4xo2fa/npm_release_indexr_create_better_es6_software/)

---

Would be much more interesting if it did named exports. I have literally never wanted to export an array of modules as an index. Two problems:
How am I supposed to know which modules are at which index?

``` javascript
const [a, c] = require('./');
```

What if module b gets added to a folder that contains a and c? If I rerun indexr, I'll have code that should point at c (position 1 in the old array) and now points at b (position 1 in the new array). This is very bad.
The index I really want lets me do this:

``` javascript
import {
  a,
  c,
} from './';
```

Though even then, I'd want to test my build process to verify that it properly tree-shakes imported but unused modules. And since imports can have side-effects, I'm not sure that could always work.

**Comment by ryardley** [comment]
Tree shaking is not going to happen as part of this particular task. However it may happen in the future as:
1. It would mean incorporating some kind of ES6 static analyser (may be necessary at a later point.)
2. If we were doing static analysis there would be problems where indexr would be changing the module dependency graph causing infinite regress.

Named exports however is pretty easy.

**Comment by appsforartists** [comment]
indexr shouldn't do tree shaking.  Let {closure,flow,webpack,etc.} do that.

**Comment by ryardley** [comment]
It should allow for exclusions however which you sort of can do with globs now but I would like to provide a neater interface going forward.

**Comment by ryardley** [comment]
Added named exports functionality so I am going to be closing this.
